In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df = pd.read_csv("breast-cancer-wisconsin.csv")

In [3]:
df.head()

id  clump_thickness  unif_cell_size  unif_cell_shape  \
0  1000025                5               1                1   
1  1002945                5               4                4   
2  1015425                3               1                1   
3  1016277                6               8                8   
4  1017023                4               1                1   

   marginal_adhesion  single_epith_cell_size bare_nuclei  bland_chromatin  \
0                  1                       2           1                3   
1                  5                       7          10                3   
2                  1                       2           2                3   
3                  1                       3           4                3   
4                  3                       2           1                3   

   normal_nucleoli  mitoses  class  
0                1        1      2  
1                2        1      2  
2                1        1      2  
3                7        1      2  
4                1        1      2

In [4]:
df['bare_nuclei'].replace('?',np.nan,inplace=True)

In [5]:
df.isnull().sum()

id                         0
clump_thickness            0
unif_cell_size             0
unif_cell_shape            0
marginal_adhesion          0
single_epith_cell_size     0
bare_nuclei               16
bland_chromatin            0
normal_nucleoli            0
mitoses                    0
class                      0
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df = df.astype(int)

In [8]:
df.drop(['id'],axis=True,inplace=True)

In [9]:
X = df[['clump_thickness','unif_cell_size','unif_cell_shape',
        'marginal_adhesion','single_epith_cell_size','bare_nuclei','bland_chromatin',
        'normal_nucleoli','mitoses']]
Y = df[['class']]

In [10]:
X_Train,X_Test,Y_Train,Y_Test = train_test_split(X,Y,test_size = 0.2)

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [12]:
regressor.fit(X_Train, Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
# Predicting the Test set results
y_pred = regressor.predict(X_Test)
regressor.score(X_Test , Y_Test)

0.8616918210197789

In [14]:
y_pred = [round(num[0]) for num in y_pred]

In [17]:
a = regressor.predict([[5,1,1,1,2,1,3,1,1]])

In [20]:
a

array([[2.17991338]])

In [22]:
round(a[0][0])

2.0

In [46]:
print(confusion_matrix(Y_Test,y_pred))

[[88  4  0  0]
 [ 0  0  0  0]
 [ 1 12 30  2]
 [ 0  0  0  0]]


In [47]:
print(classification_report(Y_Test,y_pred))

              precision    recall  f1-score   support

         2.0       0.99      0.96      0.97        92
         3.0       0.00      0.00      0.00         0
         4.0       1.00      0.67      0.80        45
         5.0       0.00      0.00      0.00         0

    accuracy                           0.86       137
   macro avg       0.50      0.41      0.44       137
weighted avg       0.99      0.86      0.92       137



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
